src/Server/Processors/AeTitleJobProcessor.cs
src/Server/Test/Unit/Processors/AeTitleJobProcessorTest.cs

Fixes #9  .
Fix Enum parsing for JobPriority to ignore case.
**Ready**

[#9] Fix priority parsing in AeTitleJobProcessor

---

src/Server/Processors/AeTitleJobProcessor.cs
src/Server/Services/Scp/ApplicationEntityHandler.cs
src/Server/Services/Scp/ApplicationEntityManager.cs

Fixes #12  .
A few sentences describing the changes proposed in this pull request.
**Ready**

[#12] Explicitly dispose deleted job processors

---

codecov.yml
src/run-tests.sh

Enable CodeCov integration and export unit test results in opencover format.

Enable CodeCov

---

.github/workflows/build.yml
src/run-tests.sh

Combines multiple codecov reports into a single call.

Fix codecov paths

---

helm-chart/dicom-adapter/Chart.yaml
helm-chart/dicom-adapter/templates/clusterrole.yaml
helm-chart/dicom-adapter/templates/clusterrolebinding.yaml
helm-chart/dicom-adapter/templates/config-map.yaml
helm-chart/dicom-adapter/templates/crd-claraAeTitles.yaml
helm-chart/dicom-adapter/templates/crd-destinations.yaml
helm-chart/dicom-adapter/templates/crd-sources.yaml
helm-chart/dicom-adapter/templates/deployment.yaml
helm-chart/dicom-adapter/templates/service.yaml
helm-chart/dicom-adapter/templates/serviceaccount.yaml
helm-chart/dicom-adapter/templates/volume-claim.yaml
helm-chart/dicom-adapter/templates/volume.yaml
helm-chart/dicom-adapter/values.yaml

Updates helm chart files to use Apache 2
**Ready**

Update helm char license to Apache 2

---

Dockerfile

Temporary fix for CVE-2020-1971 until MS releases an updated container image.
**Ready**

Fix CVE-2020-1971

---

docs/api/rest.md
docs/changelog.md
docs/setup/ae-title-job-processor.md
docs/setup/job-processors.md
docs/setup/schema.md
docs/setup/setup.md

Fixes # .
A few sentences describing the changes proposed in this pull request.

[doc] Make copyedits to the Dicom Adapter docs

---

docs/setup/schema.md
docs/setup/setup.md
helm-chart/dicom-adapter/files/appsettings.json
src/Configuration/ConfigurationValidator.cs
src/Configuration/ScuConfiguration.cs
src/Configuration/Test/ConfigurationValidatorTest.cs
src/Server/Services/Config/K8sCrdMonitorService.cs
src/Server/Services/Http/CrdCrudControllerBase.cs
src/appsettings.json
test/dicom-test-pipeline/main.py

Outdated configuration files and docs caused some settings to be ignored when loading.
**Ready**

Fix outdated configuration docs

---

src/run-tests-in-docker.sh

Run unit/integration test in .NET 3.x docker image.
**Ready**

Use interactive terminal if available

---

docs/setup/schema.md
docs/setup/setup.md
helm-chart/dicom-adapter/files/appsettings.json
src/Configuration/ConfigurationValidator.cs
src/Configuration/ScuConfiguration.cs
src/Configuration/Test/ConfigurationValidatorTest.cs
src/Server/Services/Config/K8sCrdMonitorService.cs
src/Server/Services/Http/CrdCrudControllerBase.cs
src/appsettings.json
test/dicom-test-pipeline/main.py

Cherrypick #33 into release/0.8.1
**Ready**
- [] [Documentation comments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments) included/updated.

Cherry pick doc fixes for 0.8.1

---

src/API/Test/Nvidia.Clara.Dicom.API.Test.csproj
src/Common/Test/Nvidia.Clara.Dicom.Common.Test.csproj
src/Configuration/Test/Nvidia.Clara.Dicom.Configuration.Test.csproj
src/DicomWebClient/Test/Nvidia.Clara.Dicom.DicomWebClient.Test.csproj
src/Server/Test/Integration/Nvidia.Clara.DicomAdapter.Test.Integration.csproj
src/Server/Test/IntegrationCrd/Nvidia.Clara.DicomAdapter.Test.IntegrationCrd.csproj
src/Server/Test/Unit/Nvidia.Clara.DicomAdapter.Test.Unit.csproj
src/run-tests.sh

Switch from JUnit test reports to dotnet TRX reports.

Switch to TRX test reports

---

.github/workflows/build.yml

Use `.trx` file extension
**Ready**

Fix file upload pattern

---

.github/workflows/build.yml
src/API/Test/Nvidia.Clara.Dicom.API.Test.csproj
src/Common/Test/Nvidia.Clara.Dicom.Common.Test.csproj
src/Configuration/Test/Nvidia.Clara.Dicom.Configuration.Test.csproj
src/DicomWebClient/Test/Nvidia.Clara.Dicom.DicomWebClient.Test.csproj
src/Server/Test/Integration/Nvidia.Clara.DicomAdapter.Test.Integration.csproj
src/Server/Test/IntegrationCrd/Nvidia.Clara.DicomAdapter.Test.IntegrationCrd.csproj
src/Server/Test/Unit/Nvidia.Clara.DicomAdapter.Test.Unit.csproj
src/coverlet.runsettings
src/run-tests.sh

* Remove XUnit Reporting to GitHub Action.
* Use XPlat data collector for coverage reports.

Remove xUnit Reports

---

.github/workflows/build.yml
src/API/Test/Nvidia.Clara.Dicom.API.Test.csproj
src/Common/Test/Nvidia.Clara.Dicom.Common.Test.csproj
src/Configuration/Test/Nvidia.Clara.Dicom.Configuration.Test.csproj
src/DicomWebClient/Test/Nvidia.Clara.Dicom.DicomWebClient.Test.csproj
src/Server/Test/Integration/Nvidia.Clara.DicomAdapter.Test.Integration.csproj
src/Server/Test/IntegrationCrd/Nvidia.Clara.DicomAdapter.Test.IntegrationCrd.csproj
src/Server/Test/Unit/Nvidia.Clara.DicomAdapter.Test.Unit.csproj
src/coverlet.runsettings
src/run-tests.sh

Cherrypick #39 into release/0.8.1 branch.
**Ready**

[Cherrypick] CI changes to release 0.8.1

---

.github/workflows/build.yml
docs/setup/schema.md
docs/setup/setup.md
helm-chart/dicom-adapter/templates/deployment.yaml
helm-chart/dicom-adapter/templates/service.yaml
helm-chart/dicom-adapter/values.yaml

* Extracted DICOM SCP port & WWW port to `values.yaml`
* Update setup.md to provide instructions on where to modify DICOM SCP port.

Provide instructions to change SCP port

---

.github/workflows/build.yml
docs/setup/schema.md
docs/setup/setup.md
helm-chart/dicom-adapter/templates/deployment.yaml
helm-chart/dicom-adapter/templates/service.yaml
helm-chart/dicom-adapter/values.yaml

[Cherry-pick] Update setup doc with instructions to configure SCP port

---

.github/workflows/build.yml
build-helm-chart.sh
build/.props
helm-chart/ngc/overview.md
ngc/overview.md
src/API/Rest/InferenceRequest.cs
src/API/Rest/InferenceRequestDetails.cs
src/API/Test/Nvidia.Clara.Dicom.API.Test.csproj
src/Common/Nvidia.Clara.Dicom.Common.csproj
src/Common/Test/Nvidia.Clara.Dicom.Common.Test.csproj
src/Common/Test/RequiredIfAttributeTest.cs
src/Configuration/Nvidia.Clara.Dicom.Configuration.csproj
src/DicomWebClient/API/IQidoService.cs
src/DicomWebClient/API/IServiceBase.cs
src/DicomWebClient/CLI/Nvidia.Clara.Dicom.DicomWeb.Client.CLI.csproj
src/DicomWebClient/CLI/Qido.cs
src/DicomWebClient/Services/QidoService.cs
src/DicomWebClient/Test/QidoServiceTest.cs
src/Nvidia.Clara.Dicom.Unit.sln
src/Nvidia.Clara.Dicom.sln
src/Server/Nvidia.Clara.DicomAdapter.csproj
src/Server/Services/Jobs/DataRetrievalService.cs
src/Server/Services/Jobs/JobStore.cs
src/Server/Test/Integration/Nvidia.Clara.DicomAdapter.Test.Integration.csproj
src/Server/Test/IntegrationCrd/Nvidia.Clara.DicomAdapter.Test.IntegrationCrd.csproj
src/Server/Test/Unit/AssemblyInfo.cs
src/Server/Test/Unit/Nvidia.Clara.DicomAdapter.Test.Unit.csproj
src/Server/Test/Unit/Services/Job/DataRetrievalServiceTest.cs
src/Server/Test/Unit/Services/Job/JobSubmissionServiceTest.cs

Support ACR query & retrieve with Patient ID & Accession Number
**Ready**

ACR API - Fetch by PatientID & AccessionNumber

---

docs/setup/setup.md
helm-chart/dicom-adapter/crds/crd-inferenceRequests.yaml
helm-chart/dicom-adapter/crds/crd-inferenceRequestsArchive.yaml
helm-chart/dicom-adapter/crds/crd-jobs.yaml
src/Server/Services/Http/CrdCrudControllerBase.cs

* Improve `create aet` validation messages and update setup guide
* Move & update CRDs for helm 3 upgrade
**Ready**

Create AET doc updates & Move CRDs for helm 3

---

build-helm-chart.sh
docs/api/rest.md
docs/changelog.md
src/API/IClaraService.cs
src/API/Rest/HealthStatusResponse.cs
src/API/Rest/InferenceStatusResponse.cs
src/Server/Common/CustomResourceWatcher.cs
src/Server/Program.cs
src/Server/Services/Config/K8sCrdMonitorService.cs
src/Server/Services/Disk/SpaceReclaimerService.cs
src/Server/Services/Export/ExportServiceBase.cs
src/Server/Services/Http/HealthController.cs
src/Server/Services/Http/InferenceController.cs
src/Server/Services/Jobs/DataRetrievalService.cs
src/Server/Services/Jobs/IInferenceRequestStore.cs
src/Server/Services/Jobs/InferenceRequestStore.cs
src/Server/Services/Jobs/JobStore.cs
src/Server/Services/Jobs/JobSubmissionService.cs
src/Server/Services/Scp/ScpService.cs
src/Server/Services/Scp/ScpServiceInternal.cs
src/Server/Test/Unit/Services/Http/InferenceControllerTest.cs
src/Server/Test/Unit/Services/Job/InferenceRequestStoreTest.cs

New Restful APIs:
* `/health/status`: includes number of active DIMSE assoiations and statuses of all services.
* `/health/ready` & `/health/live`
*In Progress*

Health check API

---

README.md
docs/open-source-licenses.md
docs/toc.yml
src/Server/Nvidia.Clara.DicomAdapter.csproj

Include open source licenses in the user guide.

Update open source licenses and link in user guide

---

src/Server/Program.cs

Disable console log colors to avoid printing escape chars.
**Ready**

Disable console log colors

---

docs/setup/setup.md
helm-chart/dicom-adapter/files/appsettings.json
src/Server/Program.cs
src/Server/Services/Http/ClaraAeTitleController.cs
src/Server/Services/Http/DestinationAeTitleController.cs
src/Server/Services/Http/SourceAeTitleController.cs
src/Server/appsettings.json

Control console logging color in appsettings.
**Ready**

Control console color in appsettings

---

docs/api/rest/config.md
docs/setup/ae-title-job-processor.md
src/API/Rest/InferenceRequest.cs
src/Common/ExtensionMethods.cs
src/Common/Test/ExtensionMethodsTest.cs
src/Server/Processors/AeTitleJobProcessor.cs

* Remove PHI from generated job name.
* Increase length of job name limit to 63 characters
**Ready**

Remove PHI from job name and increase job name length

---

src/Configuration/ConfigurationValidator.cs
src/Configuration/ServicesConfiguration.cs
src/Server/Repositories/ClaraPayloadsApi.cs
src/Server/Services/Jobs/JobSubmissionService.cs
src/Server/Test/Unit/Repositories/ClaraPayloadsApiTest.cs

Fixes #63  .
Fix per review feedback made in #63

Fix review feedback

---

src/API/Rest/InferenceRequest.cs
src/API/Test/InferenceRequestTest.cs
src/Server/Services/Disk/SpaceReclaimerService.cs
src/Server/Services/Jobs/DataRetrievalService.cs
src/Server/Test/Unit/Services/Http/InferenceControllerTest.cs
src/Server/Test/Unit/Services/Job/DataRetrievalServiceTest.cs

* Fix to remove retrieved ACR payloads once a job is submitted.
* Validate transactionId
**Ready**

Remove downloaded ACR payloads

---

src/API/InferenceJob.cs
src/Database/InferenceJobConfiguration.cs
src/Database/Migrations/20210420185743_InitialCreate.Designer.cs
src/Database/Migrations/20210420185743_InitialCreate.cs
src/Database/Migrations/DicomAdapterContextModelSnapshot.cs

Add a new column for primary key instead of using Job ID from Platform.
**Ready*

Schema update for InferenceJob

---

Dockerfile
src/API/IJobsRepository.cs
src/API/JobProcessorBase.cs
src/Server/Processors/AeTitleJobProcessor.cs
src/Server/Program.cs
src/Server/Repositories/ClaraJobRepository.cs
src/Server/Repositories/ClaraJobsApi.cs
src/Server/Repositories/ClaraPayloadsApi.cs
src/Server/Repositories/DicomAdapterRepository.cs
src/Server/Repositories/InferenceRequestRepository.cs
src/Server/Repositories/ResultsApi.cs
src/Server/Services/Disk/SpaceReclaimerService.cs
src/Server/Services/Export/DicomWebExportService.cs
src/Server/Services/Export/ExportServiceBase.cs
src/Server/Services/Export/ScuExportService.cs
src/Server/Services/Jobs/DataRetrievalService.cs
src/Server/Services/Jobs/JobSubmissionService.cs
src/Server/Services/Scp/ApplicationEntityHandler.cs
src/Server/Services/Scp/ApplicationEntityManager.cs
src/Server/Test/Integration/DicomAdapterFixture.cs
src/Server/Test/Integration/StoreScpTest.cs
src/Server/Test/Unit/Processors/AeTitleJobProcessorTest.cs
src/Server/Test/Unit/Services/Export/DicomWebExportServiceTest.cs
src/Server/Test/Unit/Services/Export/ExportServiceBaseTest.cs
src/Server/Test/Unit/Services/Job/DataRetrievalServiceTest.cs
src/Server/Test/Unit/Services/Job/JobSubmissionServiceTest.cs
src/Server/Test/Unit/Services/Scp/ApplicationEntityManagerTest.cs

* Reduce memory usage by explicitly detaching objects upon adding or updating with status of complete/failure.
* Update Dockerfile to include dotnet debugging tools.
* Removes files from disk after job submission reaches maximum retries.
**Ready**

Detach objects in EF to reduce memory usage

---

.github/workflows/build.yml

Update to use latest codecov action step.
**Ready**

Update codecov action
